c_char_tbl = """CREATE TABLE IF NOT EXISTS characters 
                (char_id INTEGER PRIMARY KEY,
                 guild_id INTEGER NOT NULL,
                 user_id INTEGER NOT NULL,
                 sheet_id TEXT NOT NULL,
                 portrait_url TEXT,
                 name TEXT NOT NULL,
                 archetype TEXT NOT NULL,
                 species TEXT NOT NULL,
                 gender	TEXT,
                 height TEXT,
                 weight TEXT,
                 age INTEGER,
                 strength TEXT, 
                 brawling TEXT,
                 climbing TEXT, 
                 stamina TEXT, 
                 swimming TEXT, 
                 dexterity TEXT, 
                 blaster TEXT, 
                 brawl_parry TEXT, 
                 dodge TEXT, 
                 melee_combat TEXT, 
                 melee_parry TEXT, 
                 knowledge TEXT, 
                 alien TEXT, 
                 bureaucracy TEXT, 
                 cultures TEXT, 
                 languages TEXT, 
                 planets TEXT, 
                 streetwise TEXT, 
                 value TEXT, 
                 perception TEXT, 
                 bargain TEXT, 
                 con TEXT, 
                 hide TEXT, 
                 search TEXT, 
                 sneak TEXT, 
                 mechanical TEXT, 
                 astrogation TEXT, 
                 beast TEXT, 
                 repulsor_op TEXT, 
                 transports TEXT, 
                 gunnery TEXT, 
                 shields TEXT, 
                 technical TEXT, 
                 computer TEXT, 
                 aid TEXT, 
                 repulsor_repair TEXT, 
                 security TEXT, 
                 transport_repair TEXT, 
                 movement TEXT, 
                 force_pts TEXT, 
                 force_user TEXT, 
                 dark_pts TEXT, 
                 char_pts TEXT, 
                 stunned TEXT, 
                 wounds TEXT, 
                 incapacitated TEXT, 
                 mortal_wound TEXT)"""