table_creates = ["""CREATE TABLE IF NOT EXISTS skills
                 (id INTEGER PRIMARY KEY,
                  type TEXT NOT NULL,
                  name TEXT NOT NULL,
                  sheet_name TEXT NOT NULL,
                  attribute_id INTEGER NOT NULL,
                  time TEXT NOT NULL,
                  short_time TEXT NOT NULL,
                  specialise TEXT NOT NULL,
                  descr TEXT NOT NULL,
                  specialisation TEXT);""",
                 """CREATE TABLE IF NOT EXISTS adv_skills
                 (id INTEGER PRIMARY KEY,
                  name TEXT NOT NULL,
                  sheet_name TEXT NOT NULL)""",
                 """CREATE TABLE IF NOT EXISTS force_skills
                 (id INTEGER NOT NULL,
                  name TEXT NOT NULL,
                  sheet_name TEXT NOT NULL)""",
                 """CREATE TABLE IF NOT EXISTS species
                   (id INTEGER PRIMARY KEY,
                    name TEXT NOT NULL,
                    descr TEXT NOT NULL,
                    attr_dice INTEGER NOT NULL,
                    min_move INTEGER NOT NULL,
                    max_move INTEGER NOT NULL,
                    min_dex TEXT NOT NULL,
                    max_dex TEXT NOT NULL,
                    min_know TEXT NOT NULL,
                    max_know TEXT NOT NULL,
                    min_mech TEXT NOT NULL,
                    max_mech TEXT NOT NULL,
                    min_per TEXT NOT NULL,
                    max_per TEXT NOT NULL,
                    min_str TEXT NOT NULL,
                    max_str TEXT NOT NULL,
                    min_tech TEXT NOT NULL,
                    max_tech TEXT NOT NULL);""",
                 """CREATE TABLE IF NOT EXISTS chars 
                (id INTEGER PRIMARY KEY,
                 sheet_id TEXT NOT NULL,
                 user_id INTEGER NOT NULL,
                 guild_id INTEGER NOT NULL,
                 portrait_url TEXT,
                 name TEXT NOT NULL,
                 archetype TEXT NOT NULL,
                 species_id INTEGER NOT NULL,
                 gender	TEXT,
                 height TEXT,
                 weight TEXT,
                 age INTEGER,
                 movement TEXT, 
                 force_pts TEXT, 
                 force_user TEXT, 
                 dark_pts TEXT, 
                 char_pts TEXT, 
                 stunned TEXT, 
                 wounds TEXT, 
                 incapacitated TEXT, 
                 mortal_wound TEXT);""",
                 """CREATE TABLE IF NOT EXISTS active_chars
                 (id INTEGER PRIMARY KEY,
                  user_id INTEGER NOT NULL,
                  guild_id INTEGER NOT NULL,
                  char_id INTEGER NOT NULL);""",
                 """CREATE TABLE IF NOT EXISTS char_skills
                 (char_id INTEGER NOT NULL,
                  skill_id INTEGER NOT NULL,
                  dice_code TEXT NOT NULL,
                  PRIMARY KEY (char_id, skill_id))""",
                 """CREATE TABLE IF NOT EXISTS npcs
                 (name TEXT PRIMARY KEY,
                  avatar TEXT,
                  char_id INTEGER)"""]
table_insert = 'INSERT INTO {} VALUES {};'
